[workspace]
resolver="2"
members = ["rcore","demo"]

[workspace.package]
version = "0.1.0"
authors = ["czlimx"] 
description = "am6254 processor rust language bare metal demo" 

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
